<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../build/version.props"></Import>
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>12</LangVersion>
		<PackageId>Hangfire.Redis.CSRedisCore</PackageId>
		<RootNamespace>Hangfire.Redis</RootNamespace>
		<Description>
			Hangfire Redis Storage Based on CSRedisCore
			See http://hangfire.io/ for some more info on the main project
		</Description>
	</PropertyGroup>

	<PropertyGroup>
		<OutputPath>$(MSBuildThisFileDirectory)/../../output/$(Configuration)/</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<!--移除Xml、DotSettings-->
		<None Remove="$(AssemblyName).xml" />
		<None Remove="$(AssemblyName).csproj.DotSettings" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CSRedisCore" Version="3.8.807" />
		<PackageReference Include="Hangfire.Core" Version="[1.8.0,2.0.0)" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>$(MSBuildProjectName).Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
